import './radio.css';
import {installRadioSettings} from './radio-settings';
import {installXiaozhiLink} from './xiaozhi-link';
import {api} from './radio-api';
import {LABELS,Result,add,renderResult} from './radio-results';

const field=(form:HTMLFormElement,name:string)=>(form.elements.namedItem(name) as HTMLInputElement);
const buttons=(names:string[])=>names.map(k=>`<button type="button" data-tool="${k}">${LABELS[k]}</button>`).join('');

/** The underlying Three.js scene stays alive; mouse interaction is unchanged. */
export function installRadio(monitor:HTMLElement,tower:HTMLElement,viewport:HTMLElement){
 document.title='Forge 电台';const header=document.querySelector('header')!;header.querySelector('h1')?.remove();header.querySelector('.connection')?.remove();
 const radioPanel=document.createElement('div');radioPanel.className='tower-radio-panel';radioPanel.hidden=true;
 radioPanel.innerHTML=`<nav class="tabs" aria-label="电台面板"><button data-radio-tab="desk" class="selected" aria-pressed="true">工作台</button><button data-radio-tab="persona" aria-pressed="false">人设</button><button data-radio-tab="posts" aria-pressed="false">我的帖子</button><button data-radio-tab="settings" aria-pressed="false">设置</button></nav>
 <section class="panel" data-radio-pane="desk"><h2>知乎工作台</h2><label>主题 / 问题链接<input id="radio-query" maxlength="1000" placeholder="输入主题，或使用人设兴趣"></label><button type="button" id="use-interests">使用人设兴趣</button><div class="radio-functions">${buttons(['search_zhihu','search_global','hot','answer','recommend','answers','contents','followees','favorites'])}</div><p id="radio-action-status" role="status">查询结果显示在左侧电脑</p><section id="radio-chat" class="radio-voice-controls" aria-label="奶龙语音控制"><h3>奶龙语音</h3><label class="radio-voice-device">选择设备<select id="radio-voice-device" aria-label="选择朗读和对话设备"><option value="">暂无在线设备</option></select></label><div class="radio-voice-actions"><button type="button" id="radio-read" disabled>朗读</button><button type="button" id="radio-dialogue" aria-pressed="false">开启对话</button></div><p id="radio-chat-status" role="status">查询后可朗读当前屏幕内容，也可开启机器人循环对话</p></section></section>
 <section class="panel persona-config" data-radio-pane="persona" hidden><h2>智能体 · 配置</h2><nav class="persona-tabs" aria-label="人设配置分区"><button data-persona-tab="role" aria-pressed="true">角色</button><button data-persona-tab="memory" aria-pressed="false">模型与记忆</button></nav><form id="radio-persona"><div data-persona-pane="role"><label>角色名称<input name="name" maxlength="80"></label><label>角色介绍<textarea name="persona" maxlength="4000" placeholder="性格、表达方式、价值观"></textarea></label></div><div data-persona-pane="memory" hidden><label>长期记忆<textarea name="memory" maxlength="4000" placeholder="希望奶龙持续记住的背景与边界"></textarea></label><label>兴趣与探索<textarea name="interests" maxlength="2000" placeholder="兴趣爱好，以及想探索的不同视角"></textarea></label><p>人设由Otto Master本地保存；不会自动把知乎查询内容写入记忆。</p></div><div class="persona-actions"><button type="button" id="persona-cancel">取消修改</button><button type="submit">保存人设</button></div><p role="status" id="radio-persona-status">正在读取本机配置…</p></form></section>
 <section class="panel" data-radio-pane="posts" hidden><h2>我的帖子</h2><label>内容类型<select id="content-type"><option value="all">全部创作</option><option value="pin">想法</option><option value="article">文章</option><option value="answer">回答</option><option value="zvideo">视频</option><option value="question">问题</option></select></label><button data-tool="contents">查看我的帖子</button><label>本人内容链接<input id="own-content-url" type="url" placeholder="https://www.zhihu.com/pin/…"></label><div class="radio-functions">${buttons(['detail','comments','stats','content_stats','followees','favorites','favlists'])}</div><p>只读 Access Secret 所属账号；先看列表，再按需打开全文或评论。</p></section>
 <section class="panel" data-radio-pane="settings" hidden></section>`;
 const face=tower.querySelector<HTMLElement>('.tower-face')!,originalControls=document.createElement('div');originalControls.className='simulation-controls';while(face.firstChild)originalControls.append(face.firstChild);face.append(originalControls,radioPanel);
 const lockSettings=installRadioSettings(radioPanel.querySelector<HTMLElement>('[data-radio-pane="settings"]')!);
 const actionStatus=radioPanel.querySelector<HTMLElement>('#radio-action-status')!,queryInput=radioPanel.querySelector<HTMLInputElement>('#radio-query')!,ownURL=radioPanel.querySelector<HTMLInputElement>('#own-content-url')!,readButton=radioPanel.querySelector<HTMLButtonElement>('#radio-read')!;
 const personaForm=radioPanel.querySelector<HTMLFormElement>('#radio-persona')!,personaStatus=radioPanel.querySelector<HTMLElement>('#radio-persona-status')!;
 let savedPersona:Record<string,string>={};
 const restore=()=>{for(const key of ['name','persona','memory','interests'])field(personaForm,key).value=savedPersona[key]||'';};
 api<Record<string,string>>('/v1/zhihu/persona').then(p=>{savedPersona=p;restore();personaStatus.textContent='本机配置已加载';}).catch(e=>personaStatus.textContent=e.message);
 personaForm.onsubmit=async e=>{e.preventDefault();const next={...savedPersona};new FormData(personaForm).forEach((v,k)=>next[k]=String(v));const b=personaForm.querySelector<HTMLButtonElement>('button[type="submit"]')!;b.disabled=true;try{savedPersona=await api<Record<string,string>>('/v1/zhihu/persona','PUT',next);restore();personaStatus.textContent='人设已保存到Otto Master';}catch(e){personaStatus.textContent=(e as Error).message;}finally{b.disabled=false;}};
 radioPanel.querySelector<HTMLButtonElement>('#persona-cancel')!.onclick=()=>{restore();personaStatus.textContent='已恢复保存的人设';};
 radioPanel.querySelector<HTMLButtonElement>('#use-interests')!.onclick=()=>{queryInput.value=(savedPersona.interests||'').slice(0,1000);actionStatus.textContent=queryInput.value?'已填入保存的兴趣，可修改后查询':'请先在人设中保存兴趣';};
 radioPanel.querySelectorAll<HTMLButtonElement>('[data-persona-tab]').forEach(tab=>tab.onclick=()=>{radioPanel.querySelectorAll<HTMLElement>('[data-persona-pane]').forEach(p=>p.hidden=p.dataset.personaPane!==tab.dataset.personaTab);radioPanel.querySelectorAll<HTMLButtonElement>('[data-persona-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===tab)));});
 radioPanel.querySelectorAll<HTMLButtonElement>('[data-radio-tab]').forEach(tab=>tab.onclick=()=>{face.scrollTop=0;radioPanel.querySelectorAll<HTMLElement>('[data-radio-pane]').forEach(p=>p.hidden=p.dataset.radioPane!==tab.dataset.radioTab);radioPanel.querySelectorAll<HTMLButtonElement>('[data-radio-tab]').forEach(b=>{b.classList.toggle('selected',b===tab);b.setAttribute('aria-pressed',String(b===tab));});});
 const tray=document.createElement('button');tray.type='button';tray.className='radio-drive';tray.setAttribute('aria-label','弹出光驱，进入电台');tray.setAttribute('aria-pressed','false');tray.innerHTML='<span class="drive-slot"><span class="drive-tray"><span class="drive-disc"></span><span class="drive-front"><span class="drive-label">硬件测试台</span><span>⏏</span></span></span></span>';tower.append(tray);
 const blackout=document.createElement('div');blackout.className='radio-blackout radio-web';blackout.hidden=true;blackout.setAttribute('aria-label','电台浏览器');blackout.innerHTML='<div class="radio-web-bar"><span>Forge Browser</span><span class="radio-web-address">forge://home</span><span class="radio-web-badge">知乎官方只读 API</span></div><div class="radio-web-page" tabindex="0" aria-label="网页内容"><h2>让好奇心接入知乎</h2><p>从主机选择只读查询，也可选择一台EVA朗读结果或进入循环对话。</p><p>机器人离线不影响查询。没有凭据或授权时会明确提示，不展示虚构结果。</p></div><div class="radio-live-transcript" role="status"></div>';viewport.append(blackout);
 const page=blackout.querySelector<HTMLElement>('.radio-web-page')!,xiaozhi=installXiaozhiLink(header,radioPanel,blackout.querySelector<HTMLElement>('.radio-live-transcript')!);
 let ejected=false,lastResult:Result|null=null,requesting=false;
 tray.onclick=()=>{ejected=!ejected;tray.classList.toggle('ejected',ejected);tray.setAttribute('aria-pressed',String(ejected));tray.setAttribute('aria-label',ejected?'收回光驱，返回 3D 调试':'弹出光驱，进入电台');tray.querySelector('.drive-label')!.textContent=ejected?'AI社区':'硬件测试台';monitor.classList.toggle('radio-mode',ejected);blackout.hidden=!ejected;originalControls.hidden=ejected;radioPanel.hidden=!ejected;face.scrollTop=0;if(!ejected)lockSettings();monitor.querySelector('.stage-toolbar')?.toggleAttribute('inert',ejected);for(const node of Array.from(viewport.children))if(node!==blackout)node.toggleAttribute('inert',ejected);};
 const render=(result:Result)=>{lastResult=result;readButton.disabled=false;blackout.querySelector('.radio-web-address')!.textContent='forge://'+result.tool;renderResult(page,result,(tool,args)=>void runQuery(tool,args));};
 readButton.onclick=()=>{if(lastResult)void xiaozhi.readResult(lastResult);};
 async function runQuery(tool:string,args:Record<string,unknown>={}){
  if(requesting)return;requesting=true;actionStatus.textContent='查询中…';radioPanel.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.disabled=true);
  try{const result=await api<Result>('/v1/zhihu/query','POST',{tool,arguments:args});render(result);actionStatus.textContent='已显示知乎官方查询结果';}catch(e){const message=(e as Error).message;actionStatus.textContent=message;page.replaceChildren();add(page,'h2',LABELS[tool]||'查询');add(page,'p',message,'radio-web-notice');}finally{requesting=false;radioPanel.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.disabled=false);}
 }
 radioPanel.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>{const tool=b.dataset.tool!,args:Record<string,unknown>={};if(['search_zhihu','search_global','answer','recommend'].includes(tool)){const q=queryInput.value.trim()||(savedPersona.interests||'').slice(0,1000);if(q)args.query=q;}if(tool==='answers')args.url=queryInput.value.trim();if(['detail','comments','content_stats'].includes(tool))args.url=ownURL.value.trim();if(tool==='contents')args.content_type=radioPanel.querySelector<HTMLSelectElement>('#content-type')!.value;void runQuery(tool,args);});
 void api<{configured:boolean}>('/v1/zhihu/status').then(s=>{actionStatus.textContent=s.configured?'知乎官方API已配置，可开始查询':'请先在Server环境配置 ZHIHU_ACCESS_SECRET';}).catch(e=>actionStatus.textContent=e.message);
}
