import {api,hasConsoleAuthorization,setConsoleToken} from './radio-api';

type ComponentState={enabled?:boolean;healthy?:boolean;state?:string;[key:string]:unknown};
type Health={status:string;version:string;checked_at:string;components:Record<string,ComponentState>};
type SystemStatus={state:string;project:string;version:string;started_at:string;uptime_seconds:number;current_time:string;platform:{system:string;release:string;python:string};web_url:string;discovery_hostname:string;http_port:number;mqtt_port:number;console_auth_configured:boolean};
type MqttStatus={state:string;healthy?:boolean;enabled?:boolean;connected_clients?:number;port?:number;public_endpoint?:string;last_error?:string|null;[key:string]:unknown};
type Device={device_id:string;name?:string;status:string;transport?:string;firmware_version?:string;ip_address?:string;last_heartbeat_at?:string|null;action_state?:string;current_action?:string|null;actions_count?:number;sound_busy?:boolean|null};
type Conversation={device_id:string;name:string;device_status:string;transport:string|null;session_id:string|null;state:string;user_partial:string;user_text:string;assistant_text:string;tool_status:string|null;action:string|null;error_code:string|null};
type Firmware={available:boolean;version:string|null;target_hardware:string|null;size:number|null;sha256:string|null;download_url:string|null;reason:string|null};
type BatchItem={device_id:string;accepted:boolean;command_id?:string;status?:string;error?:{code:string;message:string}};
type BatchResult={requested:number;accepted:number;failed:number;items:BatchItem[]};
type ActionCatalog={device_id:string;items:Array<{name?:string}|string>;count:number};

const actionDefinitions=[
 {name:'walk',label:'↑ 前进',direction:1},{name:'walk',label:'↓ 后退',direction:-1},{name:'turn',label:'↶ 左转',direction:1},{name:'turn',label:'↷ 右转',direction:-1},{name:'jump',label:'⌃ 跳跃',direction:1},{name:'swing',label:'↔ 左右摇摆',direction:1},{name:'moonwalk',label:'◁ 太空步',direction:1},{name:'jitter',label:'≈ 抖一抖',direction:1},{name:'bend',label:'⌄ 弯腰',direction:1},{name:'laugh',label:'♪ 大笑',direction:1},{name:'home',label:'⌂ 复位',direction:1},
] as const;

const labels:Record<string,string>={healthy:'正常',running:'运行中',online:'在线',idle:'空闲',degraded:'降级',connecting:'连接中',stale:'状态过期',offline:'离线',disabled:'已禁用',stopped:'已停止',missing:'未配置',unknown:'未知',waiting:'等待',laughing:'大笑',listening:'监听',recognizing:'识别',answering:'回答',failed:'失败'};
const tone=(state:string)=>['healthy','running','online','idle','waiting'].includes(state)?'ok':['connecting','laughing','listening','recognizing','answering'].includes(state)?'pending':['degraded','stale','stopped','missing','unknown'].includes(state)?'warn':'bad';
const text=(value:unknown,fallback='—')=>value===null||value===undefined||value===''?fallback:String(value);
const node=<K extends keyof HTMLElementTagNameMap>(tag:K,className='',content='')=>{const item=document.createElement(tag);if(className)item.className=className;if(content)item.textContent=content;return item;};
const badge=(state:string,label?:string)=>{const item=node('span','server-badge '+tone(state),label||labels[state]||state);item.dataset.state=state;return item;};
const metric=(label:string,value:unknown,detail='')=>{const item=node('div','server-metric');item.append(node('span','server-metric-label',label),node('strong','',text(value)));if(detail)item.append(node('small','',detail));return item;};
const card=(title:string)=>{const item=node('section','server-card');item.append(node('h3','',title));return item;};
const formatDuration=(seconds:number)=>{const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return hours?`${hours} 小时 ${minutes} 分钟`:`${minutes} 分钟`;};
const actionName=(item:string|{name?:string})=>typeof item==='string'?item:item.name||'';
const selectedDeviceIds=new Set<string>();

export function installServerConsole(){
 const root=document.getElementById('server-console');if(!root)return;
 root.innerHTML='<div class="server-head"><div><h2>Otto Master Server</h2><p>真实控制面 · 浏览器不直连 MQTT</p></div><div><span class="server-badge warn" id="server-auth-state">控制未授权</span> <span class="server-badge warn" id="server-live-state">未连接</span></div></div><nav class="server-tabs" aria-label="Server 控制台分区"><button type="button" data-server-tab="overview" aria-pressed="true">总览</button><button type="button" data-server-tab="devices" aria-pressed="false">设备</button><button type="button" data-server-tab="commands" aria-pressed="false">命令</button><button type="button" data-server-tab="settings" aria-pressed="false">设置</button><button type="button" data-server-tab="firmware" aria-pressed="false">固件</button></nav><div id="server-view" class="server-view" aria-live="polite"></div>';
 const view=root.querySelector<HTMLElement>('#server-view')!,live=root.querySelector<HTMLElement>('#server-live-state')!,authState=root.querySelector<HTMLElement>('#server-auth-state')!;
 let active='overview',destroyed=false,refreshing=false;
 const renderAuth=()=>{const allowed=hasConsoleAuthorization();authState.className='server-badge '+(allowed?'ok':'warn');authState.textContent=allowed?'标签页已带令牌':'控制未授权';};
 const setLive=(state:string,label?:string)=>{live.className='server-badge '+tone(state);live.textContent=label||labels[state]||state;};
 const fail=(message:string)=>{setLive('failed','未连接');view.replaceChildren();const item=card('无法读取 Server');item.append(node('p','',message),node('small','','请启动Otto Master；浏览器不会回退为直连MQTT。'));view.append(item);};
 const requireAuth=()=>{if(hasConsoleAuthorization())return true;window.alert('当前标签页没有有效控制令牌，命令未发送。请在“设置”中应用令牌。');return false;};
 const batchSummary=(result:BatchResult)=>result.items.map(item=>item.accepted?`${item.device_id}: ${item.status||'accepted'}`:`${item.device_id}: ${item.error?.message||'failed'}`).join('；')||`${result.accepted}/${result.requested} 台接受`;

 async function renderOverview(){
  const [health,system,mqtt,devices,firmware]=await Promise.all([api<Health>('/v1/health'),api<SystemStatus>('/v1/system/status'),api<MqttStatus>('/v1/mqtt/status'),api<{items:Device[]}>('/v1/devices'),api<Firmware>('/v1/firmware')]);
  const conversations=hasConsoleAuthorization()?await api<{items:Conversation[];active_count:number}>('/v1/conversations').catch(()=>({items:[],active_count:0})):{items:[],active_count:0};
  setLive(health.status);view.replaceChildren();
  const summary=node('section','server-summary '+tone(health.status));const title=node('div','server-summary-title');const line=node('div','server-summary-state');line.append(node('i','server-status-dot'),node('strong','',health.status==='healthy'?'Otto Master 正常':'Otto Master 降级'));title.append(line,node('span','',`${system.platform.system} ${system.platform.release} · Python ${system.platform.python}`));const kpis=node('div','server-kpi-strip');kpis.append(metric('在线设备',devices.items.filter(item=>item.status==='online').length,`共 ${devices.items.length} 台`),metric('MQTT连接',mqtt.connected_clients??0,mqtt.state),metric('活跃对话',conversations.active_count,hasConsoleAuthorization()?'私有投影':'需授权'),metric('运行时间',formatDuration(system.uptime_seconds),`v${system.version}`));summary.append(title,kpis);
  const grid=node('div','server-overview-grid');const access=card('服务入口');access.append(metric('控制台',system.web_url),metric('mDNS',system.discovery_hostname),metric('HTTP / MQTT',`${system.http_port} / ${system.mqtt_port}`));const components=card('组件健康');const list=node('div','server-component-list');for(const [name,state] of Object.entries(health.components)){const row=node('div','server-component');const identity=node('div','server-component-name');identity.append(node('i','server-component-dot '+tone(state.healthy===true?'healthy':state.enabled===false?'disabled':state.state||'failed')),node('span','',name));row.append(identity,badge(state.healthy===true?'healthy':state.state||'unknown'));list.append(row);}components.append(list);const current=card('当前设备');if(!devices.items.length)current.append(node('p','server-empty','等待设备 hello + heartbeat'));else for(const device of devices.items.slice(0,6))current.append(deviceRow(device,true));grid.append(access,components,current);
  const lanes=card('设备对话');if(!hasConsoleAuthorization())lanes.append(node('p','server-empty','用户语音文字受保护；应用控制令牌后显示。'));else if(!conversations.items.length)lanes.append(node('p','server-empty','暂无设备对话。'));else{const laneGrid=node('div','server-lane-grid');for(const lane of conversations.items){const item=node('article','server-lane'),head=node('div','server-lane-head'),who=node('div');who.append(node('strong','',lane.name),node('code','',lane.device_id));head.append(who,badge(lane.state));const user=node('div','server-speech user');user.append(node('small','','用户'),node('strong','',lane.user_partial||lane.user_text||'等待用户说话…'));const assistant=node('div','server-speech assistant');assistant.append(node('small','','奶龙'),node('strong','',lane.assistant_text||lane.action||'等待回答…'));item.append(head,node('p','server-lane-meta',`${lane.device_status} · ${lane.transport||'—'} · ${lane.session_id||'无会话'}`),user,assistant);laneGrid.append(item);}lanes.append(laneGrid);}
  const ota=card('固件');ota.append(metric('状态',firmware.available?'可下载':firmware.reason||'未配置'),metric('版本',firmware.version),metric('目标',firmware.target_hardware));if(firmware.available&&firmware.download_url){const link=node('a','server-download','下载已校验固件') as HTMLAnchorElement;link.href=firmware.download_url;ota.append(link);}view.append(summary,grid,lanes,ota);
 }

 function deviceRow(device:Device,compact=false){
  const item=node('article','server-device'),head=node('div','server-device-heading'),identity=node('div');identity.append(node('strong','',device.name||device.device_id),node('code','',device.device_id));head.append(identity,badge(device.status));item.append(head);const facts=node('div','server-device-facts');facts.append(metric('传输',device.transport),metric('动作',device.current_action||device.action_state||'—'),metric('固件',device.firmware_version),metric('IP（诊断）',device.ip_address));item.append(facts);
  if(!compact){const actions=node('div','server-device-actions'),verify=node('button','','只读验证') as HTMLButtonElement,stop=node('button','server-stop','停止') as HTMLButtonElement;verify.type='button';stop.type='button';verify.disabled=device.status!=='online'||!hasConsoleAuthorization();stop.disabled=!['online','stale','connecting'].includes(device.status)||!hasConsoleAuthorization();verify.onclick=async()=>{if(!requireAuth())return;verify.disabled=true;try{const result=await api<{passed:boolean;checks:unknown[]}>(`/v1/devices/${device.device_id}/verify`,'POST',{});window.alert(result.passed?`验证通过：${result.checks.length} 项`:'验证未通过');}catch(error){window.alert((error as Error).message);}finally{verify.disabled=false;}};stop.onclick=async()=>{if(!requireAuth()||!window.confirm(`确认停止 ${device.name||device.device_id}？`))return;stop.disabled=true;try{await api(`/v1/devices/${device.device_id}/stop`,'POST',{});window.alert('停止命令已进入服务端');}catch(error){window.alert((error as Error).message);}finally{stop.disabled=false;}};actions.append(verify,stop);item.append(actions);}return item;
 }

 async function renderDevices(){const data=await api<{items:Device[]}>('/v1/devices');setLive('healthy','已连接');view.replaceChildren();const section=card('设备与连接');if(!data.items.length)section.append(node('p','server-empty','暂无设备。'));else for(const device of data.items)section.append(deviceRow(device));view.append(section);}

 async function renderCommands(){
  const [deviceData,eventData]=await Promise.all([api<{items:Device[]}>('/v1/devices'),api<{items:Array<{cursor:number;event?:{topic?:string;payload?:unknown}}>}>('/v1/events?limit=20')]);const online=deviceData.items.filter(device=>device.status==='online');for(const id of [...selectedDeviceIds])if(!online.some(device=>device.device_id===id))selectedDeviceIds.delete(id);const catalogEntries=await Promise.all(online.map(async device=>{const catalog=await api<ActionCatalog>(`/v1/devices/${device.device_id}/actions`).catch(()=>({device_id:device.device_id,items:[],count:0}));return [device.device_id,new Set(catalog.items.map(actionName).filter(Boolean))] as const;}));const catalogs=new Map(catalogEntries);view.replaceChildren();
  const shell=node('section','server-batch'),head=node('div','server-command-head'),heading=node('div'),selectedCount=node('span','server-selection-count');heading.append(node('p','server-eyebrow','MULTI-DEVICE CONTROL'),node('h3','','多设备批量控制'));head.append(heading,selectedCount);shell.append(head);const targetList=node('div','server-target-list'),targetTools=node('div','server-target-tools'),selectOnline=node('button','','选择在线设备') as HTMLButtonElement,clear=node('button','','清空选择') as HTMLButtonElement;selectOnline.type='button';clear.type='button';targetTools.append(selectOnline,clear);shell.append(targetTools,targetList);
  const controls=node('div','server-quick-panel');controls.innerHTML='<div class="server-quick-parameters"><label>步数<input name="steps" type="number" min="1" max="100" value="3"></label><label>速度 ms<input name="speed" type="number" min="500" max="1500" value="1000"></label><label>幅度<input name="amount" type="number" min="0" max="170" value="50"></label></div>';const quick=node('div','server-quick-grid'),status=node('p','server-command-status','请先选择设备');status.setAttribute('role','status');const field=(name:string)=>controls.querySelector<HTMLInputElement>(`[name="${name}"]`)!;
  const commonActions=()=>{const ids=[...selectedDeviceIds];if(!ids.length)return new Set<string>();const first=new Set(catalogs.get(ids[0])||[]);for(const id of ids.slice(1))for(const action of [...first])if(!catalogs.get(id)?.has(action))first.delete(action);return first;};
  const actionButtons:Array<{button:HTMLButtonElement;name:string}>=[],independentButtons:HTMLButtonElement[]=[];
  const paint=()=>{targetList.replaceChildren();selectedCount.textContent=`已选 ${selectedDeviceIds.size} 台`;clear.disabled=!selectedDeviceIds.size;for(const device of deviceData.items){const label=node('label','server-target-option'+(device.status==='online'?'':' unavailable')),input=node('input') as HTMLInputElement;input.type='checkbox';input.disabled=device.status!=='online';input.checked=selectedDeviceIds.has(device.device_id);input.onchange=()=>{input.checked?selectedDeviceIds.add(device.device_id):selectedDeviceIds.delete(device.device_id);paint();};const info=node('span','server-target-info');info.append(node('strong','',device.name||device.device_id),node('code','',device.device_id));label.append(input,info,badge(device.status));targetList.append(label);}const common=commonActions();for(const item of actionButtons)item.button.disabled=!hasConsoleAuthorization()||!selectedDeviceIds.size||!common.has(item.name);for(const button of independentButtons)button.disabled=!hasConsoleAuthorization()||!selectedDeviceIds.size;status.textContent=!hasConsoleAuthorization()?'当前标签页未授权，命令不会发送':selectedDeviceIds.size?`共同动作 ${common.size} 个`:'请先选择在线设备';};
  const send=async(path:string,body:Record<string,unknown>,button:HTMLButtonElement)=>{if(!requireAuth()||!selectedDeviceIds.size)return;button.disabled=true;status.textContent='命令正在进入Otto Dispatcher…';try{const result=await api<BatchResult>(path,'POST',{...body,device_ids:[...selectedDeviceIds],confirmation:true});status.textContent=batchSummary(result);}catch(error){status.textContent=(error as Error).message;}finally{paint();}};
  for(const action of actionDefinitions){const button=node('button','server-quick-action',action.label) as HTMLButtonElement;button.type='button';button.onclick=()=>void send('/v1/commands/actions/batch',{action:action.name,parameters:{steps:Number(field('steps').value),speed:Number(field('speed').value),direction:action.direction,amount:Number(field('amount').value)}},button);actionButtons.push({button,name:action.name});quick.append(button);}const stop=node('button','server-quick-action server-danger','■ 立即停止') as HTMLButtonElement;stop.type='button';stop.onclick=()=>{if(window.confirm(`确认停止已选择的 ${selectedDeviceIds.size} 台设备？`))void send('/v1/commands/stops/batch',{},stop);};independentButtons.push(stop);quick.append(stop);controls.append(quick);const conversation=node('div','server-conversation-control');conversation.append(node('strong','','循环对话'));for(const command of ['start','stop'] as const){const button=node('button',command==='stop'?'server-stop':'',command==='start'?'开启对话':'退出对话') as HTMLButtonElement;button.type='button';button.onclick=()=>void send('/v1/commands/conversations/batch',{command},button);independentButtons.push(button);conversation.append(button);}controls.append(conversation,status);shell.append(controls);selectOnline.onclick=()=>{online.forEach(device=>selectedDeviceIds.add(device.device_id));paint();};clear.onclick=()=>{selectedDeviceIds.clear();paint();};paint();
  const history=card('最近事件');const list=node('div','server-event-list');if(!eventData.items.length)list.append(node('p','server-empty','暂无事件'));else for(const frame of [...eventData.items].reverse()){const row=node('article','server-event');row.append(node('strong','',frame.event?.topic||'unknown'),node('code','',`#${frame.cursor}`),node('span','',JSON.stringify(frame.event?.payload||{}).slice(0,180)));list.append(row);}history.append(list);view.append(shell,history);
 }

 async function renderSettings(){
  const settings=await api<{server:{host:string;port:number;console_auth_configured:boolean};mqtt:{enabled:boolean;host:string;port:number};discovery:{enabled:boolean;hostname:string};logging:{level:string}} >('/v1/settings');view.replaceChildren();const form=node('form','server-settings') as HTMLFormElement;form.innerHTML=`<section><h3>控制授权</h3><label>当前标签页令牌<input name="console_token" type="password" autocomplete="off" placeholder="不会写入磁盘"></label><button type="button" name="apply_token">应用令牌</button><button type="button" name="clear_token">清除令牌</button><small>服务端已配置：${settings.server.console_auth_configured?'是':'否'}</small></section><section><h3>只读运行参数</h3><p>HTTP ${settings.server.host}:${settings.server.port}</p><p>MQTT ${settings.mqtt.host}:${settings.mqtt.port}</p><p>mDNS ${settings.discovery.hostname}</p><small>端口与监听地址由 config.yaml 管理。</small></section><section><h3>可保存覆盖</h3><label>日志级别<select name="logging_level"><option>DEBUG</option><option>INFO</option><option>WARNING</option><option>ERROR</option></select></label><label class="server-check"><input name="discovery_enabled" type="checkbox">启用mDNS发现</label><button type="submit">保存并在重启后应用</button><p role="status"></p></section>`;const token=form.elements.namedItem('console_token') as HTMLInputElement,logging=form.elements.namedItem('logging_level') as HTMLSelectElement,discovery=form.elements.namedItem('discovery_enabled') as HTMLInputElement,message=form.querySelector<HTMLElement>('[role="status"]')!;logging.value=settings.logging.level;discovery.checked=settings.discovery.enabled;(form.elements.namedItem('apply_token') as HTMLButtonElement).onclick=()=>{setConsoleToken(token.value);token.value='';renderAuth();message.textContent='令牌已应用到当前标签页；受保护请求将由Server验证。';};(form.elements.namedItem('clear_token') as HTMLButtonElement).onclick=()=>{setConsoleToken('');token.value='';renderAuth();message.textContent='当前标签页令牌已清除。';};form.onsubmit=async event=>{event.preventDefault();if(!requireAuth())return;const button=form.querySelector<HTMLButtonElement>('button[type="submit"]')!;button.disabled=true;try{const result=await api<{effect:string}>('/v1/settings','PUT',{logging_level:logging.value,discovery_enabled:discovery.checked});message.textContent=result.effect==='server_restart_required'?'已保存，重启Server后应用':'已保存';}catch(error){message.textContent=(error as Error).message;}finally{button.disabled=false;}};view.append(form);
 }

 async function renderFirmware(){const firmware=await api<Firmware>('/v1/firmware');view.replaceChildren();const item=card('可发布固件');item.append(metric('状态',firmware.available?'可下载':firmware.reason),metric('版本',firmware.version),metric('目标硬件',firmware.target_hardware),metric('大小',firmware.size?`${firmware.size} bytes`:'—'),metric('SHA-256',firmware.sha256));if(firmware.available&&firmware.download_url){const link=node('a','server-download','下载固件') as HTMLAnchorElement;link.href=firmware.download_url;item.append(link);}view.append(item);}

 async function refresh(){if(refreshing||destroyed)return;refreshing=true;renderAuth();try{if(active==='overview')await renderOverview();else if(active==='devices')await renderDevices();else if(active==='commands')await renderCommands();else if(active==='settings')await renderSettings();else await renderFirmware();}catch(error){fail((error as Error).message);}finally{refreshing=false;}}
 root.querySelectorAll<HTMLButtonElement>('[data-server-tab]').forEach(button=>button.onclick=()=>{active=button.dataset.serverTab!;root.querySelectorAll<HTMLButtonElement>('[data-server-tab]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));view.replaceChildren(node('p','server-loading','正在读取Otto Master…'));void refresh();});window.addEventListener('otto-auth-change',()=>void refresh());renderAuth();view.append(node('p','server-loading','正在读取Otto Master…'));void refresh();const timer=window.setInterval(()=>{const pane=root.closest<HTMLElement>('[data-pane="server"]');if(!pane?.hidden&&['overview','devices'].includes(active))void refresh();},4000);window.addEventListener('pagehide',()=>{destroyed=true;window.clearInterval(timer);},{once:true});
}
