import {api,hasConsoleAuthorization,setConsoleAuthRequired} from './radio-api';
import {plain,Result} from './radio-results';

type Device={device_id:string;name?:string;status:string;transport?:string};
type Conversation={device_id:string;state:string;user_partial?:string;user_text?:string;assistant_text?:string};
type SystemStatus={console_auth_required:boolean};

export function installXiaozhiLink(header:HTMLElement,panel:HTMLElement,transcript:HTMLElement){
 const connection=document.createElement('div');connection.className='device-link';connection.innerHTML='<div class="system-status" aria-label="连接状态"><span class="status-item"><span class="device-indicator" data-role="device-indicator" data-status="offline"></span><span data-role="device-count">设备 0</span></span><span class="status-item"><span class="device-indicator" data-role="api-indicator" data-status="offline"></span><span data-role="api-status">Server 未连接</span></span></div><span class="device-status visually-hidden" role="status">Server 未连接</span><button type="button">刷新</button>';header.prepend(connection);
 const refreshButton=connection.querySelector('button')!,status=connection.querySelector<HTMLElement>('.device-status')!,indicator=connection.querySelector<HTMLElement>('[data-role="device-indicator"]')!,deviceCount=connection.querySelector<HTMLElement>('[data-role="device-count"]')!,apiIndicator=connection.querySelector<HTMLElement>('[data-role="api-indicator"]')!,apiStatus=connection.querySelector<HTMLElement>('[data-role="api-status"]')!,dialogueButton=panel.querySelector<HTMLButtonElement>('#radio-dialogue')!,voiceDevice=panel.querySelector<HTMLSelectElement>('#radio-voice-device')!,chatStatus=panel.querySelector<HTMLElement>('#radio-chat-status')!;
 let dialogue=false,statusTimer=0,ended=false;

 const selected=()=>voiceDevice.value;
 const selectedLabel=()=>voiceDevice.selectedOptions[0]?.textContent||'未选择设备';
 const syncDialogue=()=>{dialogueButton.textContent=dialogue?'退出对话':'开启对话';dialogueButton.setAttribute('aria-pressed',String(dialogue));dialogueButton.classList.toggle('active',dialogue);};
 const loadDevices=(items:Device[])=>{const previous=voiceDevice.value;voiceDevice.replaceChildren();for(const device of items){const option=document.createElement('option');option.value=device.device_id;option.textContent=`${device.name||device.device_id} · ${device.status} · ${device.transport||'—'}`;option.disabled=device.status!=='online';voiceDevice.append(option);}const available=Array.from(voiceDevice.options).filter(option=>!option.disabled);if(available.some(option=>option.value===previous))voiceDevice.value=previous;else if(available[0])voiceDevice.value=available[0].value;dialogueButton.disabled=!selected()||!hasConsoleAuthorization();};
 const refreshStatus=async()=>{try{const [health,deviceData,system]=await Promise.all([api<{status:string}>('/v1/health'),api<{items:Device[]}>('/v1/devices'),api<SystemStatus>('/v1/system/status')]);setConsoleAuthRequired(system.console_auth_required);const online=deviceData.items.filter(item=>item.status==='online');apiIndicator.dataset.status=health.status==='healthy'?'online':'pending';apiStatus.textContent=health.status==='healthy'?'Otto Server 在线':'Otto Server 降级';deviceCount.textContent=`设备 ${online.length}/${deviceData.items.length}`;indicator.dataset.status=online.length?'online':'offline';status.textContent='Otto Master 已连接';loadDevices(deviceData.items);if(hasConsoleAuthorization()){const conversations=await api<{items:Conversation[]}>('/v1/conversations').catch(()=>({items:[]}));const current=conversations.items.find(item=>item.device_id===selected());dialogue=Boolean(current&&current.state!=='waiting'&&current.state!=='failed');syncDialogue();if(current){transcript.textContent=[current.user_partial||current.user_text,current.assistant_text].filter(Boolean).join('\n奶龙：');}}else{dialogue=false;syncDialogue();chatStatus.textContent='Server安全模式未授权';}}catch(error){apiIndicator.dataset.status='offline';apiStatus.textContent='Server 未连接';deviceCount.textContent='设备 0';indicator.dataset.status='offline';status.textContent=(error as Error).message;dialogueButton.disabled=true;}};
 const requireDevice=()=>{const deviceId=selected();if(!deviceId){chatStatus.textContent='没有可用的在线设备';return null;}if(!hasConsoleAuthorization()){chatStatus.textContent='Server安全模式未授权，命令未发送';return null;}return deviceId;};
 const resultSpeech=(result:Result)=>{const data=result.data||{},items=Array.isArray(data.Items)?data.Items.slice(0,3):Array.isArray(data.items)?data.items.slice(0,3):[];const excerpt=plain(data.Text??data.Body??items.map((item:any)=>[item.Title??item.title,item.ContentText??item.Summary??item.summary??item.Comment?.Content??item.Headline].filter(Boolean).join('：')).join('。'));return `${result.title}。${excerpt||'当前结果没有可朗读的文字摘要。'}`.slice(0,600);};

 dialogueButton.onclick=async()=>{const deviceId=requireDevice();if(!deviceId)return;dialogueButton.disabled=true;const command=dialogue?'stop':'start';chatStatus.textContent=command==='start'?`${selectedLabel()}：正在进入循环对话…`:`${selectedLabel()}：正在退出对话…`;try{const result=await api<{accepted:number;failed:number;items:Array<{error?:{message:string}}>}>('/v1/commands/conversations/batch','POST',{device_ids:[deviceId],command,confirmation:true});if(result.accepted!==1)throw Error(result.items[0]?.error?.message||'设备未接受对话命令');dialogue=command==='start';syncDialogue();chatStatus.textContent=dialogue?'设备已接受对话命令，等待真实语音状态':'设备已接受退出命令';}catch(error){chatStatus.textContent=(error as Error).message;}finally{dialogueButton.disabled=!hasConsoleAuthorization()||!selected();window.setTimeout(()=>void refreshStatus(),800);}};
 voiceDevice.onchange=()=>{dialogue=false;syncDialogue();chatStatus.textContent=`已选择：${selectedLabel()}`;void refreshStatus();};
 refreshButton.onclick=()=>{refreshButton.disabled=true;void refreshStatus().finally(()=>refreshButton.disabled=false);};
 window.addEventListener('otto-auth-change',()=>void refreshStatus());syncDialogue();void refreshStatus();statusTimer=window.setInterval(()=>void refreshStatus(),5000);
 window.addEventListener('pagehide',()=>{ended=true;window.clearInterval(statusTimer);},{once:true});

 return {async readResult(result:Result){const deviceId=requireDevice();if(!deviceId)return;chatStatus.textContent=`${selectedLabel()}：正在通过现有 TTS 链路朗读…`;try{await api('/v1/zhihu/narrate','POST',{device_id:deviceId,text:resultSpeech(result)});chatStatus.textContent='朗读已完成';}catch(error){chatStatus.textContent=(error as Error).message;}if(!ended)void refreshStatus();}};
}
